# Generated by Django 3.0.3 on 2020-05-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='Phone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
