# Generated by Django 3.0.3 on 2020-05-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0004_trucks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='Phone',
            field=models.CharField(default=0, help_text='Contact phone number', max_length=15),
        ),
    ]
