# Generated by Django 3.0.3 on 2020-05-28 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0005_auto_20200524_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_As', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), size=None)),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Stipend', models.IntegerField(blank=True, null=True)),
                ('Country', models.CharField(default='India', max_length=50)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=255)),
                ('Speciality', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None), size=None)),
                ('Type', models.CharField(max_length=15)),
                ('ExpertIn', models.CharField(max_length=100)),
                ('License', models.CharField(max_length=5)),
                ('Base', models.CharField(blank=True, max_length=100, null=True)),
                ('EmployeeID', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, max_length=255, null=True, upload_to='picture/')),
            ],
        ),
    ]
