# Generated by Django 3.0.6 on 2020-05-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0006_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordered_Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
