# Generated by Django 3.0.6 on 2020-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0010_reviewtruck'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewChef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Review', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewOutlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Review', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Review', models.CharField(max_length=1024)),
            ],
        ),
    ]
