# Generated by Django 3.0.6 on 2020-06-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0011_reviewchef_reviewoutlet_reviewvenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewVenueID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Review', models.CharField(max_length=1024)),
            ],
        ),
    ]
