# Generated by Django 3.0.6 on 2020-05-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0011_auto_20200531_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='venue',
        ),
    ]
