# Generated by Django 3.0.6 on 2020-05-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0014_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodwagon_backend.Chef'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodwagon_backend.Venues'),
        ),
    ]
