# Generated by Django 3.0.6 on 2020-05-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0016_remove_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='venue',
        ),
    ]
