# Generated by Django 3.0.6 on 2020-06-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0014_reviewtruckid'),
        ('foodwagon_backend', '0022_remove_orderitemtruck_date_added'),
    ]

    operations = [
    ]
