# Generated by Django 3.0.6 on 2020-06-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0023_merge_20200601_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venues',
            name='Phone',
        ),
    ]
