# Generated by Django 3.0.6 on 2020-06-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0024_remove_venues_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='Phone',
            field=models.CharField(default=0, help_text='Contact phone number', max_length=15),
        ),
    ]
