# Generated by Django 3.0.6 on 2020-06-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0025_venues_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venues',
            name='Phone',
        ),
    ]
