# Generated by Django 3.0.6 on 2020-06-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0025_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
