# Generated by Django 3.0.6 on 2020-06-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0027_venues_phone'),
        ('foodwagon_backend', '0027_auto_20200609_1445'),
    ]

    operations = [
    ]
