# Generated by Django 3.0.6 on 2020-06-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodwagon_backend', '0028_merge_20200611_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemchef',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='orderitemvenue',
            name='date_added',
        ),
    ]
